# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEPLOYMENT
# -----------------------------------------------------------------------------
# https://hub.docker.com/r/heartexlabs/label-studio
# -----------------------------------------------------------------------------
version: '3'

volumes:
  data:
    driver: local

services:
  labelstudio:
    restart: always
    image: heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data
    ports:
      - 8123:8080
    volumes:
      - ./data:/label-studio/data